# Choose: "hf" or "gemini"
PROVIDER = "hf"

# If using Hugging Face
HUGGINGFACE_API_TOKEN = "hf_xxx_put_your_token_here"

# If using Gemini
GOOGLE_API_KEY = "AIza_xxx_put_your_key_here"

# Optional: override models
HF_MODEL_ID = "mistralai/Mixtral-8x7B-Instruct-v0.1"
GEMINI_MODEL_ID = "gemini-1.5-flash"
